# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id_file', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Importação',
                'managed': True,
                'verbose_name': 'Upload Planilha Bolsa de Estudos',
                'db_table': 'DataFile',
            },
        ),
        migrations.CreateModel(
            name='ScholarshipInfo',
            fields=[
                ('id_bolsa', models.AutoField(primary_key=True, serialize=False)),
                ('vl_ano', models.IntegerField()),
                ('nm_estado', models.CharField(max_length=2)),
                ('nm_municipio', models.CharField(max_length=64)),
                ('nm_programa_fomento', models.CharField(max_length=32)),
                ('nm_instituicao_ensino_superior', models.CharField(max_length=32)),
                ('nm_programa', models.CharField(max_length=64)),
                ('nm_area_avaliacao', models.CharField(max_length=64)),
                ('nm_area_conhecimento', models.CharField(max_length=64)),
                ('nm_grande_area', models.CharField(max_length=64)),
                ('vl_coordenador_geral_isf', models.IntegerField()),
                ('vl_coordenador_pedagogico_isf', models.IntegerField()),
                ('vl_coordenador_centro_isf', models.IntegerField()),
                ('vl_doutorado', models.IntegerField()),
                ('vl_iniciacao_cientifica', models.IntegerField()),
                ('vl_mestrado', models.IntegerField()),
                ('vl_mestrado_profissional', models.IntegerField()),
                ('vl_professor_nacional_senior', models.IntegerField()),
                ('vl_professor_isf', models.IntegerField()),
                ('vl_pos_doc', models.IntegerField()),
                ('vl_supervisao', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Bolsas de Estudos',
                'verbose_name': 'Bolsa de Estudo',
                'db_table': 'ScholarshipInfo',
            },
        ),
    ]
